create table DB_CURRENCY_TEST (
      id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL ,
      currency varchar_ignorecase(50) not null,
      content varchar_ignorecase(128) not null);

create unique index idx_currency_content on DB_CURRENCY_TEST (currency,content);

